name: Run Broadcaster
on:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
      - name: curl
        uses: wei/curl@master
        with:
          args: ${{ secrets.APP_URL }}
